CREATE TABLE SINGER (
       ID INT NOT NULL AUTO_INCREMENT
     , FIRST_NAME VARCHAR2(60) NOT NULL
     , LAST_NAME VARCHAR2(40) NOT NULL
     , BIRTH_DATE DATE
     , PRIMARY KEY (ID)
     , CONSTRAINT UQ_SINGER_1 UNIQUE (FIRST_NAME, LAST_NAME)
);

CREATE TABLE ALBUM (
       ID INT NOT NULL AUTO_INCREMENT
     , SINGER_ID INT NOT NULL
     , TITLE VARCHAR2(100) NOT NULL
     , RELEASE_DATE DATE
     , PRIMARY KEY (ID)
     , CONSTRAINT FK_ALBUM FOREIGN KEY (SINGER_ID)
                  REFERENCES SINGER (ID)
     , CONSTRAINT UQ_SINGER_ALBUM_1 UNIQUE (SINGER_ID, TITLE)
);